CREATE TABLE IF NOT EXISTS file_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_file_categories_name ON file_categories (name);

INSERT INTO file_categories (name, description, created_at, updated_at)
VALUES
    ('Документи', 'Різні документи', now(), now()),
    ('Відео', 'Файли відеоформату', now(), now()),
    ('Лінки', 'Лише покликання', now(), now()),
    ('Світлини', 'Файли формату зображень', now(), now())

ON CONFLICT (name) DO UPDATE
SET
    description = EXCLUDED.description,
    updated_at = now();

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'media_resources'
          AND column_name = 'category_id'
    ) THEN
        ALTER TABLE media_resources
            DROP CONSTRAINT IF EXISTS fk_media_resources_category_id;

        ALTER TABLE media_resources
            RENAME COLUMN category_id TO file_category_id;

        UPDATE media_resources mr
        SET file_category_id = fc.id
        FROM categories c
        JOIN file_categories fc ON fc.name = c.name
        WHERE mr.file_category_id = c.id;

        DROP INDEX IF EXISTS idx_media_resources_category_id;
    END IF;
END $$;

ALTER TABLE media_resources
    ADD CONSTRAINT fk_media_resources_file_category_id
        FOREIGN KEY (file_category_id)
            REFERENCES file_categories(id)
            ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_media_resources_file_category_id
    ON media_resources (file_category_id);


