CREATE TABLE IF NOT EXISTS specialties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    number VARCHAR(255),
    about VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_specialties_name ON specialties (name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_specialties_number ON specialties (number);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_categories_name ON categories (name);

CREATE TABLE IF NOT EXISTS file_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_file_categories_name ON file_categories (name);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name VARCHAR(255),
    first_name VARCHAR(255),
    email VARCHAR(255),
    password VARCHAR(255),
    avatar_link VARCHAR(255),
    group_name VARCHAR(255),
    bio VARCHAR(500),
    github_link VARCHAR(255),
    status VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    role VARCHAR(255),
    specialty_id BIGINT,
    CONSTRAINT fk_users_specialty_id
        FOREIGN KEY (specialty_id)
            REFERENCES specialties(id)
            ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_users_specialty_id ON users (specialty_id);

CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    likes INTEGER,
    is_anonymous BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    category_id BIGINT,
    user_id BIGINT,
    CONSTRAINT fk_posts_category_id
        FOREIGN KEY (category_id)
            REFERENCES categories(id)
            ON DELETE SET NULL,
    CONSTRAINT fk_posts_user_id
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_posts_category_id ON posts (category_id);
CREATE INDEX IF NOT EXISTS idx_posts_user_id ON posts (user_id);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(255),
    language VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    user_id BIGINT,
    post_id BIGINT,
    CONSTRAINT fk_comments_user_id
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE SET NULL,
    CONSTRAINT fk_comments_post_id
        FOREIGN KEY (post_id)
            REFERENCES posts(id)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments (user_id);
CREATE INDEX IF NOT EXISTS idx_comments_post_id ON comments (post_id);

CREATE TABLE IF NOT EXISTS post_user_likes (
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (post_id, user_id),
    CONSTRAINT fk_post_user_likes_post_id
        FOREIGN KEY (post_id)
            REFERENCES posts(id)
            ON DELETE CASCADE,
    CONSTRAINT fk_post_user_likes_user_id
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255),
    message VARCHAR(255),
    is_read BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    user_id BIGINT,
    CONSTRAINT fk_notifications_user_id
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications (user_id);

CREATE TABLE IF NOT EXISTS faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question VARCHAR(255) NOT NULL,
    answer TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS media_resources (
    id UUID PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(255),
    url VARCHAR(255),
    views INTEGER,
    type VARCHAR(255),
    file_category_id BIGINT,
    created_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_media_resources_file_category_id ON media_resources (file_category_id);

CREATE TABLE IF NOT EXISTS media_resource_file_urls (
    media_resource_id UUID NOT NULL,
    position INTEGER NOT NULL,
    file_url VARCHAR(255) NOT NULL,
    PRIMARY KEY (media_resource_id, position),
    CONSTRAINT fk_media_resource_file_urls_media_resource_id
        FOREIGN KEY (media_resource_id)
            REFERENCES media_resources(id)
            ON DELETE CASCADE
);
