CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    credits INTEGER,
    taught_by VARCHAR(255),
    semester INTEGER,
    syllabus_link TEXT,
    block_type VARCHAR(255),
    exam_type VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

