CREATE TABLE subjects
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    credits       INTEGER,
    taught_by     VARCHAR(255),
    semester      INTEGER,
    syllabus_link VARCHAR(255),
    block_type    VARCHAR(255),
    exam_type     VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    specialty_id  BIGINT,
    CONSTRAINT pk_subjects PRIMARY KEY (id)
);

ALTER TABLE subjects
    ADD CONSTRAINT FK_SUBJECTS_ON_SPECIALTY FOREIGN KEY (specialty_id) REFERENCES specialties (id);

DROP TABLE file_metadata CASCADE;

DROP TABLE lecturer CASCADE;